# Generated by Django 5.1.1 on 2025-03-24 14:09

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('description', tinymce.models.HTMLField()),
                ('image', models.ImageField(default=None, max_length=500, null=True, upload_to='destinations/')),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('rating', models.FloatField()),
                ('precautions', models.TextField()),
            ],
        ),
    ]
