# Generated by Django 3.2.23 on 2025-04-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='duration_hours',
            field=models.FloatField(default=2.0, help_text='Average time (in hours) a visitor spends here.'),
        ),
    ]
