# Generated by Django 5.1.1 on 2025-03-20 16:56

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.FileField(default=None, max_length=500, null=True, upload_to='city/')),
                ('category', models.CharField(max_length=50)),
                ('description', tinymce.models.HTMLField()),
            ],
        ),
    ]
